jobs:
  include:
    - stage: deploy
      name: "Python 3.9 on Windows"
      if: tag IS NOT blank
      os: windows    
      language: shell
      before_install:
        - choco install python --version=3.9.5
        - choco install innosetup
        - python -m pip install --upgrade pip
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
      install:
        - pip install -r requirements.txt
        - pip install pyinstaller
      script:
        - pyinstaller gotify-tray.spec
        - iscc gotify-tray.iss
        - mv "inno-output\gotify-tray-installer.exe" "gotify-tray-installer-win.exe"
      deploy:
        provider: releases
        edge: true
        cleanup: false
        api_key: $GITHUB_TOKEN
        file: gotify-tray-installer-win.exe
        on:
          tags: true
    - stage: deploy
      name: "Python 3.9 on ubuntu focal"
      if: tag IS NOT blank
      os: linux
      dist: focal
      language: python
      python: 3.9
      before_install:
        - pip install --upgrade pip
      install:
        - pip install -r requirements.txt
        - pip install pyinstaller
      script:
        - make build
        - cp dist/gotify-tray_amd64.deb gotify-tray_amd64_focal.deb
      deploy:
        provider: releases
        edge: true
        cleanup: false
        api_key: $GITHUB_TOKEN
        file: gotify-tray_amd64_focal.deb
        on:
          tags: true
